version: '3.6'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
    - 5432:5432
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: utfpr
    extra_hosts:
    - "host.docker.internal:host-gateway"
      
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
    - postgres
    ports:
    - 5050:80
    ## you can change pgAdmin default username/password with below environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    extra_hosts:
    - "host.docker.internal:host-gateway"

volumes:
  db_data:

  # graphql-engine:
  #   image: hasura/graphql-engine:v2.4.0
  #   ports:
  #   - "8081:8080"
  #   depends_on:
  #   - "postgres"
  #   restart: always
  #   environment:
  #     ## postgres database to store Hasura metadata
  #     HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:notreve@postgres:5432/postgres
  #     ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
  #     PG_DATABASE_URL: postgres://postgres:notreve@postgres:5432/postgres
  #     ## enable the console served by server
  #     HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
  #     ## enable debugging mode. It is recommended to disable this in production
  #     HASURA_GRAPHQL_DEV_MODE: "true"
  #     HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
  #     ## uncomment next line to set an admin secret
  #     HASURA_GRAPHQL_ADMIN_SECRET: notreve
  #     HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "dancocontighoSharedSecret_dancocontighoSharedSecret"}'
  #   extra_hosts:
  #   - "host.docker.internal:host-gateway"
# volumes:
#   db_data:
